// Building type radio buttons
const ResidentialButton = document.getElementById("Residential-button")
const CommercialButton = document.getElementById("Commercial-button")
const IndustrialButton = document.getElementById("Industrial-button")


// Product tier radio buttons
const standard = document.getElementById("Standard")
const premium = document.getElementById("Premium")
const excellium = document.getElementById("Excellium")


//Final output fields
const elevatorsrequired = document.getElementById("elevatorsrequired")
const costperunit = document.getElementById("costperunit")
const installationfees = document.getElementById("Installation Fees")
const totalcost = document.getElementById("totalcost")

// container section 
const apartmentsInputDiv = document.getElementById("apartmentInputDiv")
const floorsInputDiv = document.getElementById("floorsInputDiv")
const elevatorsInputDiv = document.getElementById("elevatorsInputDiv")
const occupancyInputDiv = document.getElementById("occupancyInputDiv")

//input section
const apartmentInput = document.getElementById("numberofapartments")
const floorsInput = document.getElementById("numberoffloors")
const elevatorsInput = document.getElementById("numberofelevators")
const occupancyInput = document.getElementById("maximumoccupancy")

// const formatter
function formatToDollar(amount) {
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(amount);
  }
// temporarily hiding
apartmentsInputDiv.style.display = "none"
floorsInputDiv.style.display = "none"
elevatorsInputDiv.style.display = "none"
occupancyInputDiv.style.display = "none"



// hide n seek
ResidentialButton.addEventListener("click", () => {

    floorsInputDiv.style.display = "block"
    apartmentsInputDiv.style.display = "block"

    occupancyInputDiv.style.display = "none"
    elevatorsInputDiv.style.display = "none"


})

CommercialButton.addEventListener("click", () => {

    occupancyInputDiv.style.display = "block"
    floorsInputDiv.style.display = "block"

    elevatorsInputDiv.style.display = "none"
    apartmentsInputDiv.style.display = "none"


})

IndustrialButton.addEventListener("click", () => {

    elevatorsInputDiv.style.display = "block"

    occupancyInputDiv.style.display = "none"
    apartmentsInputDiv.style.display = "none"
    floorsInputDiv.style.display = "none"

})




//GETTING HOW MANY ELEVATORS THE CUSTOMER NEEDS


//Divide the number of apartments by the number of floors to obtain the average apartments per floor


//divide the average apartments per floor by 6 to get the number of required elevators


//divide the number of floors by 20 to get the number of elevator banks


//multiply the elevators required by the number of banks to get the total elevators


const residentialMath = () => {

    //The number of apartments the user has
    const numberOfApartments = apartmentInput.value
    const numberoffloors = floorsInput.value

    const avgApartmentsPerFloor = Math.ceil(numberOfApartments/numberoffloors)
    const RequiredElevators = Math.ceil(avgApartmentsPerFloor/6)
    const ElevatorBanks = Math.ceil(numberoffloors/20)
    const totalelevators = Math.ceil(ElevatorBanks*RequiredElevators)

    //visually displaying the number to the user
    elevatorsrequired.value = totalelevators
    
}


apartmentInput.addEventListener("input", () => {

    residentialMath()

})





// If building type is commercial, multiply max occupancy per floor by number of floors to obtain total number of occupants

// The number of elevators required per elevator bank is determined by dividing the total number of occupants by 200.

// The number of elevators banks required is determined by dividing the nuber of floors by 10 as opposed to 20 for residential buildings. Each elevator bank must have an additional elevator for freight.

// total elevators


const commercialMath = () => {

    const numberoffloors = floorsInput.value
    const maximumoccupancy = occupancyInput.value

    const totaloccupants = (maximumoccupancy*numberoffloors)
    const RequiredElevators = (totaloccupants/200)
    const ElevatorBanks = (numberoffloors/10 )    
    const totalelevators = (ElevatorBanks*RequiredElevators + ElevatorBanks)
    
    elevatorsrequired.value = totalelevators
}

floorsInput.addEventListener("input" , () => {

    if(ResidentialButton.checked){
        residentialMath()
    } else if (CommercialButton.checked){
        commercialMath()  
    }
    
})

occupancyInput.addEventListener("input", () => {

    commercialMath()
})




// ELEVATORS NEED; whatever they type into it is what thye need
// Industrial Math

const IndustrialMath = () =>{

    const ElevatorRequired = elevatorsInput.value

    
    elevatorsrequired.value = ElevatorRequired

}

elevatorsInput.addEventListener("input" , () => {

IndustrialMath () 

})



//4 FINAL OUTPUT FIELDS

//Number of elevators - generated by other event listeners



standard.addEventListener("click", () => {
    const unitCost = 8000
    const installationPercentage = 0.10

    //Unit cost
    costperunit.value = formatToDollar (unitCost)

    //Pre instillation cost
    const preInstallCost = unitCost *  elevatorsrequired.value

    //Instillation Fee
    const installationFee = preInstallCost * installationPercentage

    installationfees.value = formatToDollar (installationFee)

    //Total Cost
    const totalCost = preInstallCost + installationFee
    
    totalcost.value = formatToDollar (totalCost)
})



// premium
premium.addEventListener("click", () => {
const installationPercentage = .15
const unitCost = 12000


// unit cost
costperunit.value = formatToDollar (unitCost)

// preinstallation fee
const preInstallCost = unitCost * elevatorsrequired.value

// installation fee
const installationFee = preInstallCost * installationPercentage

installationfees.value = formatToDollar (installationFee)
// total cost

const totalCost = preInstallCost + installationFee

totalcost.value = formatToDollar (totalCost)
})
//excellium
excellium.addEventListener("click" , () => {
const installationPercentage = .20
const unitCost = 15000
// unit cost
costperunit.value = formatToDollar (unitCost)
// preinstallation fee
const preInstallCost = unitCost * elevatorsrequired.value
// installation fee
const installationFee = preInstallCost * installationPercentage
installationfees.value = formatToDollar (installationFee)
// total cost
const totalCost =  preInstallCost + installationFee
totalcost.value = formatToDollar (totalCost)
})